
// export const list = [
//   {
//     id: 1,
//     title: "Black pepper chicken and Rice",
//     price: 2500,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/chinese 1.jpeg",
//     amount: 1,
//     kind: "Chinese",
//   },
//   {
//     id: 2,
//     title: "Burger",
//     price: 1200,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/american 1.jpeg",
//     amount: 1,
//     kind: "American",
//   },
//   {
//     id: 3,
//     title: "Jollof Rice and Fried Plantain",
//     price: 1500,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/african 1.png",
//     amount: 1,
//     kind: "African",
//   },
//   {
//     id: 4,
//     title: "Noodle",
//     price: 2000,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/chinese 2.jpeg",
//     amount: 1,
//     kind: "Chinese",
//   },
//   {
//     id: 5,
//     title: "Hot dog",
//     price: 1000,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/american 2.jpeg",
//     amount: 1,
//     kind: "American",
//   },
//   {
//     id: 6,
//     title: "White Rice and Vegetable Sauce with Plantain",
//     price: 1700,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/african 2.jpeg",
//     amount: 1,
//     kind: "African",
//   },
//   {
//     id: 7,
//     title: "Fufu and Egusi Soup",
//     price: 2000,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/african 3.jpg",
//     amount: 1,
//     kind: "African",
//   },
//   {
//     id: 8,
//     title: "Hainanese chicken rice",
//     price: 1800,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/chinese 3.jpg",
//     amount: 1,
//     kind: "Chinese",
//   },
//   {
//     id: 9,
//     title: "Cobb salad",
//     price: 1200,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/american 3.jpeg",
//     amount: 1,
//     kind: "American",
//   },
//   {
//     id: 10,
//     title: "Baked Apple Pie",
//     price: 1500,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/american 4.jpg",
//     amount: 1,
//     kind: "American",
//   },
//   {
//     id: 11,
//     title: "Amala and Ewedu Soup",
//     price: 1500,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/african 4.jpeg",
//     amount: 1,
//     kind: "African",
//   },
//   {
//     id: 12,
//     title: "Chinese Noodles",
//     price: 2300,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/chinese 4.jpeg",
//     amount: 1,
//     kind: "Chinese",
//   },
//   {
//     id: 13,
//     title: "Vetkoek (Fried Donuts Stuffed with Minced Meat)",
//     price: 2200,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/african 5.jpg",
//     amount: 1,
//     kind: "African",
//   },
//   {
//     id: 14,
//     title: "Seswaa",
//     price: 1600,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/african 6.jpg",
//     amount: 1,
//     kind: "African",
//   },
//   {
//     id: 15,
//     title: "Bacon, Eggs and Pancakes",
//     price: 1400,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/american 5.jpg",
//     amount: 1,
//     kind: "American",
//   },
//   {
//     id: 16,
//     title: "Rice, Beans and Stew",
//     price: 1800,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/african 7.jpeg",
//     amount: 1,
//     kind: "African",
//   },
//   {
//     id: 17,
//     title: "African Salad Abacha",
//     price: 1400,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/african 8.jpeg",
//     amount: 1,
//     kind: "African",
//   },
//   {
//     id: 18,
//     title: "Kung Pao chicken",
//     price: 2000,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/chinese 5.jpeg",
//     amount: 1,
//     kind: "Chinese",
//   },
//   {
//     id: 19,
//     title: "Pancakes",
//     price: 1300,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/american 6.jpeg",
//     amount: 1,
//     kind: "America",
//   },
//   {
//     id: 20,
//     title: "Gatsby Sandwich",
//     price: 1700,
//     img: "https://im4g3s.blob.core.windows.net/img-ws/african 10.jpg",
//     amount: 1,
//     kind: "African",
//   },
// ];
